<?php
/**
 * Created by Maisondunet.
 *
 * @project     dexergie
 * @author      vincent
 * @copyright   2023 LA MAISON DU NET
 * @link        https://www.maisondunet.com
 */
/** @var CookieConsent $block */
/** @var Escaper $escaper */

use Magento\Framework\Escaper;
use Maisondunet\CookieConsent\Block\CookieConsent;

?>
<script type="text/javascript">
    window.cc_wrapper_config = <?= $block->getConfig()->getJson(); ?>;
    window.cc_wrapper_config.locales = {
        "<?= $escaper->escapeJs($block->getLocale()) ?>": "<?= $escaper->escapeJs($block->getTranslationUrl()) ?>"
    };
</script>
<script src="<?= $block->getViewFileUrl("Maisondunet_CookieConsent::js/cookie-consent.min.js") ?>"></script>
<script type="text/javascript">
    // Define dataLayer and the gtag function.
    window.dataLayer = window.dataLayer || [];
    (function () {
      try {
        let gtag = function(){dataLayer.push(arguments);}
        let default_consent = {};
        cc_wrapper_config.storage_pool.forEach((s) => {
          default_consent[s.name] = s.enabled_by_default ? "granted" : "denied"
        });
        gtag('consent', 'default', default_consent);
      } catch (e) {}
    })();
</script>
