stages:
  - deploy

deploy:
  only:
    - tags
  stage: deploy
  image: curlimages/curl:latest
  script:
    - 'curl -sS --show-error --header "Job-Token: $CI_JOB_TOKEN" --fail --data tag=${CI_COMMIT_TAG} "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/composer"'
